### PR TITLE
feat(listbox): listbox styling

### PR DESCRIPTION
**Pull request by johanlahti**
## New features:
- Apply styling of header, content and selection states (selected, alternative, excluded)
- This is accomplished using a new property called `components: object[]` which for now only allows you to override the **styling** of the following components: `header`, `content`, `palette` (for selection styling)

The `components` property could get expanded functionality in the future but currently only considering overriding styling.

## Example of using components
Here is how you can specify components to override styling of header, content and selections style:
```
[
    {
        "key": "header",
        "header": {
            "fontColor": {
                "index": -1,
                "color": "#19d956"
            },
            "fontSize": 23
        },
        "fontSize": 24,
        "fontColor": {
            "index": -1,
            "color": "#075900"
        }
    },
    {
        "key": "content",
        "content": {
            "fontSize": 18,
            "fontColor": {
                "index": -1,
                "color": "#ff2047"
            }
        },
        "fontColor": {
            "index": -1,
            "color": "#590c2a"
        },
        "fontSize": 14
    },
    {
        "key": "selections",
        "selected": {
            "index": -1,
            "color": "#4b6d98"
        },
        "selectedContrast": {
            "index": -1,
            "color": "#ffffff"
        },
        "alternative": {
            "index": -1,
            "color": "#71a5e6"
        },
        "excluded": {
            "index": -1,
            "color": "#8c8a8a"
        }
    }
]
```

### General component

And for the settings on the Filter pane level, use the general component:
```
{
        "key": "general",
        "title": {
            "main": {
                "fontSize": "16px",
                "fontStyle": [],
                "color": {
                    "index": -1,
                    "color": "#06ab00"
                }
            },
            "subTitle": {
                "fontSize": "14px",
                "color": {
                    "index": -1,
                    "color": "#8a138b"
                },
                "fontStyle": [
                    ""
                ]
            },
            "footer": {
                "color": {
                    "index": -1,
                    "color": "#ed7c4e"
                },
                "fontStyle": [
                    "underline",
                    "bold"
                ],
                "fontSize": "17px"
            }
        },
        "bgColor": {
            "color": {
                "index": 4,
                "color": "#d76c6c"
            }
        }
    },
```

### CODE REVIEW

**Comment by T-Wizard** [comment]
why change background color of seleced excluded values? (PM request?)

**Comment by johanlahti** [comment]
@T-Wizard There was no color value for selected excluded so I added it (`#A9A9A9`), is it really different from before? I picked it from Stage. What color should we use?

**Comment by T-Wizard** [comment]
> @T-Wizard There was no color value for selected excluded so I added it (`#A9A9A9`), is it really different from before? I picked it from Stage. What color should we use?

from the changed rendering test it looks like it had the same colors as excluded before this PR.

**Comment by johanlahti** [comment]
Yes, I see what you mean now. We define the color in more than one place. That should probably be reverted.

**Pull request merged**
