### PR TITLE
feat: add basic support for object conversion

### PR DESCRIPTION
**Pull request by quanho**
This PR is the first step to support object conversion.

### CODE REVIEW

**Comment by T-Wizard** [comment]
any support for a way object can indicate that they do not support object conversion?

**Comment by T-Wizard** [comment]
what about documentation?

**Comment by quanho** [comment]
> what about documentation?

Currently I put the method "convertTo" under DO_NOT_USE part. When we finish it we will have document for it.

**Comment by quanho** [comment]
> any support for a way object can indicate that they do not support object conversion?

Yes, we can support it like in sense-client.

**Review by Caele — APPROVED** [review]

**Review by T-Wizard — APPROVED** [review]

**Pull request merged**
