### PR TITLE
fix: show more button even when list box is not in selection

### PR DESCRIPTION
**Pull request by linhnguyen-qlik**
## Motivation
When we introduced the cyclic dimension we decided that the popover listbox (ListBoxInline.jsx) should not be in selection mode immediately when user open it. Therefore this [PR](https://github.com/qlik-oss/nebula.js/pull/1531) is created to fix the issue. 
However, users found it inconvenient that they have to click on a row to activate selection mode to see the more button (...). this PR fixes the issue by always showing the more button in popover list box even when it is not in selection mode.

https://github.com/qlik-oss/nebula.js/assets/111750285/3c338b66-738c-4080-bff4-11a9dd668613

## Requirements checklist

- [X] Api specification
  - [x] Ran `yarn spec`
    - [X] No changes **_OR_** API changes has been formally approved
- [ ] Unit/Component test coverage
- [ ] Correct PR title for the changes (fix, chore, feat)

When build and tests have passed:

- [ ] Add code reviewers, for example @qlik-oss/nebula-core

### CODE REVIEW

**Comment by T-Wizard** [comment]
this reason could also apply to "clear selection" button.
should that also be show in this case?

**Comment by T-Wizard** [comment]
have you considered it doing a selection this way should make the listbox enter selection mode?
(I think there are probably arguments both for and against)

**Comment by linhnguyen-qlik** [comment]
> this reason could also apply to "clear selection" button. should that also be show in this case?

Sounds reasonable, I will try to show the clear button too.

**Comment by linhnguyen-qlik** [comment]
@T-Wizard I have changed so that more button shows up even when the filter pane is not in selection mode.
The search and keyboard navigation are still broken but I am creating two separate PRs for them.

**Comment by T-Wizard** [comment]
it it intentional that this change make popups from current selelection no longer show up starting in selection mode?
(even if from engine websocket traffic they actually are in selection mode)

**Comment by linhnguyen-qlik** [comment]
> it it intentional that this change make popups from current selelection no longer show up starting in selection mode? (even if from engine websocket traffic they actually are in selection mode)

No, what I did was only active the selection mode (if not yet in selection mode) when user clicks on one of the options from the menu.

**Review by T-Wizard — APPROVED** [review]

**Review by Caele — APPROVED** [review]

**Pull request merged**
