### PR TITLE
fix: cycle cyclic dimension doesn't work when filter pane is in selec…

### PR DESCRIPTION
**Pull request by linhnguyen-qlik**
…tion mode

## Motivation
Currently, the selection is always activated immediately when  the popover in filter pane is opened. This prevents the list from re-rendering to update with new data when user steps through cyclic dimension. 

The PR changes the above behaviour. For cyclic dimension, the cyclic button will be disabled once user clicks on on the row in the list = selection is activated. 

For popover filterpane, the selection is not activated until user clicks on one of the row in the list. 
For normal filterpane the cyclic button will not be disabled if the filterpane is in selection mode. When user clicks on cyclic button it will call `selection.confirm()` before going to next field
## Requirements checklist

- [x] Api specification
  - [x] Ran `yarn spec`
    - [x] No changes **_OR_** API changes has been formally approved
- [x] Unit/Component test coverage
- [x] Correct PR title for the changes (fix, chore, feat)

When build and tests have passed:

- [x] Add code reviewers, for example @qlik-oss/nebula-core

### CODE REVIEW

**Comment by linhnguyen-qlik** [comment]
How do I update the snapshots? My laptop generates snapshot but for Mac so it might not be the same as the one coming from Linux.

**Comment by Caele** [comment]
Does the "cycling" always come from within the listbox? And if so, can't it force an update of its own data instead of checking the selectionstate?

**Comment by Caele** [comment]
> How do I update the snapshots? My laptop generates snapshot but for Mac so it might not be the same as the one coming from Linux.

I usually go to the build itself and save those generated images.

**Comment by linhnguyen-qlik** [comment]
I have no idea how to fix `ApiGovPolicy/Listbox JAVASCRIPT` , `ApiGovPolicy/Nebula Js JAVASCRIPT` and `ci/circleci: api-governance`. I don't think my changes cause API change.

**Comment by linhnguyen-qlik** [comment]
> Does the "cycling" always come from within the listbox? And if so, can't it force an update of its own data instead of checking the selectionstate?

Just for the record we agreed on how the listbox should behave when having a cyclic dimension as implemented in this PR.

**Review by Caele — APPROVED** [review]
Please do a sanity check of the mashup api as well, just so that is covered. (so not just in client usage)

**Pull request merged**
