### PR TITLE
fix: add right divider to listbox last column items

### PR DESCRIPTION
**Pull request by CostInCode**
## Motivation

Add a right divider to all the items of the last column.
Not adding it to all last items of each row, as in that case will be mis-aligned with the left dividers of previous items in the same column.
Resolves https://github.com/qlik-oss/sn-list-objects/issues/233

Screenshot with latest fix: 
Screenshot 2023-04-14 at 13 51 49

## Requirements checklist

- [ ] Api specification
  - [ ] Ran `yarn spec`
    - [ ] No changes **_OR_** API changes has been formally approved
- [ ] Unit/Component test coverage
- [ ] Correct PR title for the changes (fix, chore, feat)

When build and tests have passed:

- [ ] Add code reviewers, for example @qlik-oss/nebula-core

### CODE REVIEW

**Comment by T-Wizard** [comment]
This looks odd. I expect us to want it for all items that are last in there row. not just the very last item.
(In the image that would be X,Y,Z and not just Z)

**Comment by CostInCode** [comment]
> This looks odd. I expect us to want it for all items that are last in there row. not just the very last item. (In the image that would be X,Y,Z and not just Z)

Right, will change this way, all the items on the last column

**Review by johanlahti — APPROVED** [review]

**Comment by veinfors** [comment]
> > This looks odd. I expect us to want it for all items that are last in there row. not just the very last item. (In the image that would be X,Y,Z and not just Z)
> 
> Right, will change this way. Edit: adding divider to the items of last column, see description

Can you update the image in the description to show how it looks like with that fixed as well?

**Comment by CostInCode** [comment]
> Can you update the image in the description to show how it looks like with that fixed as well?

The image is updated with the latest fix (so the X is not getting the divider, just the items of last column, Y and Z)

**Comment by veinfors** [comment]
> > Can you update the image in the description to show how it looks like with that fixed as well?
> 
> The image in the description is updated with the latest fix (so the X is not getting the divider, just the items of last column, Y and Z)
> 
> If I add a right border also to X, will look bad as below: Screenshot 2023-04-14 at 14 49 26

Okey... No, that doesn't look good either, I would expect it to look like this ⬆️, but being correctly aligned (the last cell should have the same width as the other cells in that column that is)

**Comment by CostInCode** [comment]
closing as it needs further alignment with UX

**Pull request closed without merging**
