### PR TITLE
fix(ListBox): show detached toolbar when layout.toolbar is false

### PR DESCRIPTION
**Pull request by quanho**
## Motivation

To fix https://github.com/qlik-oss/sn-list-objects/issues/216.

## Requirements checklist

- [ ] Api specification
  - [ ] Ran `yarn spec`
    - [ ] No changes **_OR_** API changes has been formally approved
- [ ] Unit/Component test coverage
- [ ] Correct PR title for the changes (fix, chore, feat)

When build and tests have passed:

- [ ] Add code reviewers, for example @qlik-oss/nebula-core

### CODE REVIEW

**Review by DanielS-Qlik — APPROVED** [review]

**Comment by T-Wizard** [comment]
I think we are using `toolbar: false` in analytic creation and there it should not use detached toolbar

**Comment by veinfors** [comment]
> 

Good point, make sure to test so we don't change the behaviour in there before merging this

**Comment by veinfors** [comment]
> I think we are using `toolbar: false` in analytic creation and there it should not use detached toolbar

Good point! Make sure to test so this change doesn't alter the behaviour in there...

**Comment by DanielS-Qlik** [comment]
> 

In the last commit it changed to look at `layout.toolbar`

**Comment by veinfors** [comment]
The way this is implemented now means that the `toolbar` option will get overridden by the toolbar prop on the layout, meaning the option is not "applicable"/reliable for existing objects.

It's best that we clarify that in the spec for the `toolbar` option, and also throw an error in `apis/nucleus/src/components/listbox/hooks/useExistingModel.jsx` when that option is used for existing objects, as we do with other options like that...

**Review by T-Wizard — APPROVED** [review]

**Review by veinfors — APPROVED** [review]

**Pull request merged**
